### ISSUE TITLE
sortable option NOT working  version 0.0.5  ediTable.js 

### ISSUE THREAD

**Issue by mestafin** [OxiGen1001/ediTable#12]
In version v0.0.5, the `sortable` option does not work **ediTable.js** version.

The `sortable` option still works in the minified  **ediTable.min.js** version.

**Comment by MessaoudiMohammed** [comment]
Hello Mestafin, 
Thank you for your report, and i'll try to fix it as soon as possible.

**Comment by MessaoudiMohammed** [comment]
hey mestafin, i'm sorry for delay, i was working on some other stuff so i couldn't fix it early, anyway i've just fixed it,

Best regards.
